#!/usr/bin/env python3
"""Export MATLAB helpfile figures in strict ordinal order (fig_###.png)."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import shutil
import subprocess
import tempfile
from pathlib import Path

import yaml


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-manifest",
        type=Path,
        default=Path("parity/help_source_manifest.yml"),
        help="Source manifest generated by notebook tooling.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path("output/matlab_help_images"),
        help="Destination root for exported MATLAB reference images.",
    )
    parser.add_argument(
        "--report-json",
        type=Path,
        default=Path("output/matlab_help_images/report.json"),
        help="Path for MATLAB export report JSON.",
    )
    parser.add_argument(
        "--matlab-bin",
        default="matlab",
        help="MATLAB executable name/path.",
    )
    parser.add_argument(
        "--topics",
        default="",
        help="Optional comma-separated topic subset to export.",
    )
    parser.add_argument(
        "--topics-batch-size",
        type=int,
        default=0,
        help="Number of topics per MATLAB invocation (0 means all topics in one batch).",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume from existing --report-json and skip completed topics (ok/count_mismatch).",
    )
    parser.add_argument(
        "--log-dir",
        type=Path,
        default=Path("output/matlab_help_images/logs"),
        help="Directory for per-batch MATLAB stdout/stderr logs.",
    )
    parser.add_argument(
        "--batch-timeout-seconds",
        type=int,
        default=0,
        help="Per-batch MATLAB timeout in seconds (0 disables timeout).",
    )
    parser.add_argument(
        "--continue-on-error",
        action="store_true",
        help="Continue remaining batches when a batch fails/timeouts; mark affected topics as error.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only print resolved command; do not invoke MATLAB.",
    )
    return parser.parse_args()


def _quote_matlab(s: str) -> str:
    return s.replace("'", "''")


def _chunk_topics(topics: list[dict], size: int) -> list[list[dict]]:
    if size <= 0 or size >= len(topics):
        return [topics]
    return [topics[i : i + size] for i in range(0, len(topics), size)]


def _load_resume_completed(report_json: Path) -> set[str]:
    if not report_json.exists():
        return set()
    try:
        payload = json.loads(report_json.read_text(encoding="utf-8"))
    except Exception:
        return set()
    rows = payload.get("results", [])
    done: set[str] = set()
    for row in rows:
        topic = str(row.get("topic", "")).strip()
        status = str(row.get("status", "")).strip().lower()
        if topic and status in {"ok", "count_mismatch"}:
            done.add(topic)
    return done


def _build_report_row_from_topic(topic_row: dict) -> dict[str, object]:
    return {
        "topic": str(topic_row.get("topic", "")),
        "source_path": str(topic_row.get("source_path", "")),
        "source_type": str(topic_row.get("source_type", "")),
        "expected_figures": int(topic_row.get("expected_figure_count", 0)),
        "produced_figures": 0,
        "status": "missing",
        "error": "No batch result row produced.",
    }


def _write_aggregate_report(
    *,
    report_json: Path,
    output_root: Path,
    selected_topics: list[dict],
    by_topic: dict[str, dict[str, object]],
) -> None:
    ordered_results: list[dict[str, object]] = []
    for row in selected_topics:
        topic = str(row.get("topic", "")).strip()
        if not topic:
            continue
        ordered_results.append(by_topic.get(topic, _build_report_row_from_topic(row)))
    payload = {
        "generated_utc": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "output_root": str(output_root.resolve()),
        "topic_count": len(ordered_results),
        "results": ordered_results,
    }
    report_json.parent.mkdir(parents=True, exist_ok=True)
    report_json.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _iter_report_rows(rows: object) -> list[dict[str, object]]:
    if isinstance(rows, dict):
        return [rows]
    if isinstance(rows, list):
        return [row for row in rows if isinstance(row, dict)]
    return []


def main() -> int:
    args = parse_args()
    payload = yaml.safe_load(args.source_manifest.read_text(encoding="utf-8")) or {}
    topics = payload.get("topics", [])
    if not topics:
        raise RuntimeError(f"No topics in source manifest: {args.source_manifest}")
    if args.topics.strip():
        wanted = {token.strip() for token in args.topics.split(",") if token.strip()}
        topics = [row for row in topics if str(row.get("topic", "")).strip() in wanted]
        if not topics:
            raise RuntimeError(
                f"No topics matched --topics={args.topics!r} in {args.source_manifest}"
            )

    requested_topics = list(topics)

    if args.resume:
        completed = _load_resume_completed(args.report_json)
        topics = [row for row in topics if str(row.get("topic", "")).strip() not in completed]
        if not topics:
            print(f"All requested topics already completed in {args.report_json}")
            return 0

    args.output_root.mkdir(parents=True, exist_ok=True)
    args.report_json.parent.mkdir(parents=True, exist_ok=True)
    args.log_dir.mkdir(parents=True, exist_ok=True)

    run_topics = topics
    batches = _chunk_topics(run_topics, max(0, args.topics_batch_size))

    if args.dry_run:
        print(
            f"Resolved {len(run_topics)} topic(s) in {len(batches)} batch(es), "
            f"batch_size={args.topics_batch_size or len(run_topics)}"
        )
        return 0

    if shutil.which(args.matlab_bin) is None:
        raise FileNotFoundError(
            f"MATLAB executable not found on PATH: {args.matlab_bin}. "
            "Run with --dry-run to inspect command."
        )

    existing_by_topic: dict[str, dict[str, object]] = {}
    if args.resume and args.report_json.exists():
        try:
            existing = json.loads(args.report_json.read_text(encoding="utf-8"))
            for row in _iter_report_rows(existing.get("results", [])):
                topic = str(row.get("topic", "")).strip()
                if topic:
                    existing_by_topic[topic] = row
        except Exception:
            existing_by_topic = {}

    repo_root = Path(__file__).resolve().parents[2]
    matlab_fixture_dir = repo_root / "matlab" / "fixture_gen"

    with tempfile.TemporaryDirectory(prefix="nstat_matlab_manifest_") as td:
        tmp_dir = Path(td)
        for batch_idx, batch_topics in enumerate(batches, start=1):
            manifest_json = tmp_dir / f"help_source_manifest_batch_{batch_idx:03d}.json"
            batch_report_json = tmp_dir / f"report_batch_{batch_idx:03d}.json"
            manifest_json.write_text(json.dumps({"topics": batch_topics}, indent=2), encoding="utf-8")

            batch_expr = (
                f"addpath('{_quote_matlab(str(matlab_fixture_dir.resolve()))}'); "
                f"export_helpfile_figures('{_quote_matlab(str(manifest_json.resolve()))}', "
                f"'{_quote_matlab(str(args.output_root.resolve()))}', "
                f"'{_quote_matlab(str(batch_report_json.resolve()))}');"
            )
            cmd = [args.matlab_bin, "-batch", batch_expr]
            log_path = args.log_dir / f"batch_{batch_idx:03d}.log"
            proc: subprocess.CompletedProcess[str] | None = None
            timeout_error = False
            try:
                proc = subprocess.run(
                    cmd,
                    text=True,
                    capture_output=True,
                    check=False,
                    timeout=(args.batch_timeout_seconds if args.batch_timeout_seconds > 0 else None),
                )
                log_path.write_text(
                    (proc.stdout or "") + ("\n" if proc.stdout else "") + (proc.stderr or ""),
                    encoding="utf-8",
                )
            except subprocess.TimeoutExpired as exc:
                timeout_error = True
                stdout_text = exc.stdout.decode("utf-8", errors="replace") if isinstance(exc.stdout, bytes) else (exc.stdout or "")
                stderr_text = exc.stderr.decode("utf-8", errors="replace") if isinstance(exc.stderr, bytes) else (exc.stderr or "")
                log_path.write_text(
                    (stdout_text + "\n" + stderr_text).strip() + "\n",
                    encoding="utf-8",
                )

            if timeout_error or (proc is not None and proc.returncode != 0):
                for topic_row in batch_topics:
                    row = _build_report_row_from_topic(topic_row)
                    row["status"] = "error"
                    if timeout_error:
                        row["error"] = (
                            f"MATLAB batch timeout after {args.batch_timeout_seconds}s. "
                            f"See log: {log_path}"
                        )
                    else:
                        row["error"] = f"MATLAB batch failed. See log: {log_path}"
                    existing_by_topic[str(topic_row.get("topic", "")).strip()] = row
                _write_aggregate_report(
                    report_json=args.report_json,
                    output_root=args.output_root,
                    selected_topics=requested_topics,
                    by_topic=existing_by_topic,
                )
                if args.continue_on_error:
                    continue
                if timeout_error:
                    raise RuntimeError(
                        f"MATLAB batch {batch_idx} timed out after {args.batch_timeout_seconds}s. "
                        f"See {log_path}"
                    )
                raise RuntimeError(f"MATLAB batch {batch_idx} failed. See {log_path}")

            if not batch_report_json.exists():
                for topic_row in batch_topics:
                    row = _build_report_row_from_topic(topic_row)
                    row["status"] = "error"
                    row["error"] = f"Missing batch report file for batch {batch_idx}. See {log_path}"
                    existing_by_topic[str(topic_row.get("topic", "")).strip()] = row
            else:
                batch_report = json.loads(batch_report_json.read_text(encoding="utf-8"))
                for row in _iter_report_rows(batch_report.get("results", [])):
                    topic = str(row.get("topic", "")).strip()
                    if topic:
                        existing_by_topic[topic] = row
            _write_aggregate_report(
                report_json=args.report_json,
                output_root=args.output_root,
                selected_topics=requested_topics,
                by_topic=existing_by_topic,
            )

    if not args.report_json.exists():
        raise RuntimeError(f"MATLAB export did not create report file: {args.report_json}")
    print(args.report_json.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
