function TrialConfig_fixtures(outputFile)
% Generate deterministic MATLAB fixtures for the TrialConfig class.
%
% MATLAB reference: TrialConfig.m constructor/getName/setName/toStructure/fromStructure

if nargin < 1 || isempty(outputFile)
    thisFile = mfilename('fullpath');
    repoRoot = fileparts(fileparts(fileparts(thisFile)));
    outputDir = fullfile(repoRoot, 'tests', 'fixtures', 'TrialConfig');
    if exist(outputDir, 'dir') ~= 7
        mkdir(outputDir);
    end
    outputFile = fullfile(outputDir, 'basic.mat');
else
    outputDir = fileparts(outputFile);
    if exist(outputDir, 'dir') ~= 7
        mkdir(outputDir);
    end
end

covMask = {'Force', 'f_x'};
sampleRate = 2000;
history = [0.1 0.2];
ensCovHist = [0.05 0.15];
ensCovMask = [1 0; 0 1];
covLag = -1;
name = 'cfgA';

tc_default = TrialConfig();
default_covMask = tc_default.covMask;
default_sampleRate = tc_default.sampleRate;
default_history = tc_default.history;
default_ensCovHist = tc_default.ensCovHist;
default_ensCovMask = tc_default.ensCovMask;
default_covLag = tc_default.covLag;
default_name = tc_default.name;

tc_custom = TrialConfig(covMask, sampleRate, history, ensCovHist, ensCovMask, covLag, name);
custom_covMask = tc_custom.covMask;
custom_sampleRate = tc_custom.sampleRate;
custom_history = tc_custom.history;
custom_ensCovHist = tc_custom.ensCovHist;
custom_ensCovMask = tc_custom.ensCovMask;
custom_covLag = tc_custom.covLag;
custom_name = tc_custom.name;
custom_getName = tc_custom.getName();

tc_custom.setName('cfgRenamed');
custom_name_after_set = tc_custom.name;

custom_struct = tc_custom.toStructure();

tc_roundtrip = TrialConfig.fromStructure(custom_struct);
roundtrip_covMask = tc_roundtrip.covMask;
roundtrip_sampleRate = tc_roundtrip.sampleRate;
roundtrip_history = tc_roundtrip.history;
roundtrip_ensCovHist = tc_roundtrip.ensCovHist;
roundtrip_ensCovMask = tc_roundtrip.ensCovMask;
roundtrip_covLag = tc_roundtrip.covLag;
roundtrip_name = tc_roundtrip.name;
roundtrip_struct = tc_roundtrip.toStructure();

save(outputFile, ...
    'covMask', ...
    'sampleRate', ...
    'history', ...
    'ensCovHist', ...
    'ensCovMask', ...
    'covLag', ...
    'name', ...
    'default_covMask', ...
    'default_sampleRate', ...
    'default_history', ...
    'default_ensCovHist', ...
    'default_ensCovMask', ...
    'default_covLag', ...
    'default_name', ...
    'custom_covMask', ...
    'custom_sampleRate', ...
    'custom_history', ...
    'custom_ensCovHist', ...
    'custom_ensCovMask', ...
    'custom_covLag', ...
    'custom_name', ...
    'custom_getName', ...
    'custom_name_after_set', ...
    'custom_struct', ...
    'roundtrip_covMask', ...
    'roundtrip_sampleRate', ...
    'roundtrip_history', ...
    'roundtrip_ensCovHist', ...
    'roundtrip_ensCovMask', ...
    'roundtrip_covLag', ...
    'roundtrip_name', ...
    'roundtrip_struct');

fprintf('Wrote TrialConfig fixtures to %s\n', outputFile);
end
