#!/usr/bin/env python3
"""Check that every public symbol is documented in the hand-maintained helpfiles.

This is the contributor- and CI-side enforcement of the "Keeping
helpfiles current" rule documented in ``AGENT_GUIDE.md`` and
``CLAUDE.md``.

What this script catches
------------------------
For every symbol in ``nstat.__all__`` (and ``nstat.extras.__all__`` if
the extras namespace is present), verify the symbol's literal name
appears in:

1. ``AGENT_GUIDE.md`` — must mention every public-API symbol somewhere.
2. ``docs/ClassDefinitions.md`` — must list every *class* (not
   functions or exceptions; identified via :func:`inspect.isclass`).

What this script does NOT catch
-------------------------------
- ``docs/api.rst`` drift — that file is now auto-generated by Sphinx
  autosummary from ``nstat.__all__``.  No manual maintenance needed.
- ``PORTING_MAP.md`` drift — that file is a frozen snapshot per
  ``CLAUDE.md``.  It is updated only on a genuine MATLAB↔Python parity
  refresh, NOT on new Python-only additions.
- Notebook coverage — tracked separately by ``parity/notebook_fidelity.yml``.
- Whether the documentation *content* is current — only that the symbol
  is mentioned at all.  Content quality is a human judgement.

Exit codes
----------
- 0 — clean.  All public symbols are mentioned in target helpfiles.
- 1 — at least one symbol is undocumented.
- 2 — script invocation error.

Usage
-----
::

    python tools/check_helpfile_freshness.py             # default surface
    python tools/check_helpfile_freshness.py --quiet     # only print on failure
    python tools/check_helpfile_freshness.py --json      # machine-readable

Used by:

- ``.github/workflows/helpfile-check.yml`` — repo-wide gate.
- ``.pre-commit-config.yaml`` — local fast feedback.
- ``Makefile`` target ``make helpfile-check`` — manual invocation.
"""
from __future__ import annotations

import argparse
import importlib
import inspect
import json
import re
import sys
from pathlib import Path
from typing import Any

# Make ``nstat`` importable when invoked as a script (matches the
# pattern in tools/parity/diff_against_matlab.py and
# tools/check_readme_links.py).
_REPO_ROOT_FOR_IMPORT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT_FOR_IMPORT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT_FOR_IMPORT))


# ----------------------------------------------------------------------
# Public-surface discovery
# ----------------------------------------------------------------------

def collect_public_symbols() -> dict[str, list[str]]:
    """Return {namespace: [symbol_names...]} for the public API surface.

    Always includes ``nstat`` (the core namespace).  Adds
    ``nstat.extras`` only if the package exists and exposes its own
    ``__all__`` — this keeps the checker forward-compatible with the
    Phase-A architecture (core + extras monorepo).
    """
    surface: dict[str, list[str]] = {}

    core = importlib.import_module("nstat")
    surface["nstat"] = sorted(getattr(core, "__all__", []))

    try:
        extras = importlib.import_module("nstat.extras")
    except ImportError:
        return surface
    extras_all = list(getattr(extras, "__all__", []))
    if extras_all:
        surface["nstat.extras"] = sorted(extras_all)
    return surface


def symbol_is_class(namespace: str, symbol: str) -> bool:
    """Return True if ``namespace.symbol`` is a class (not function/exception).

    Exceptions are excluded — they're catalogued separately in
    ``api.rst`` Exceptions section and don't need a ClassDefinitions
    entry.
    """
    module = importlib.import_module(namespace)
    try:
        obj = getattr(module, symbol)
    except AttributeError:
        return False
    if not inspect.isclass(obj):
        return False
    # Exclude built-in exceptions (subclasses of BaseException).
    if issubclass(obj, BaseException):
        return False
    return True


# ----------------------------------------------------------------------
# Doc-file scanning
# ----------------------------------------------------------------------

def _read_text(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def _symbol_pattern(symbol: str) -> re.Pattern[str]:
    """Match the symbol as a whole word.

    Word-boundary regex avoids ``Signal`` matching ``SignalObj``.  We
    accept the symbol surrounded by typical Markdown / prose
    delimiters: whitespace, backtick, comma, period, paren, etc.
    """
    return re.compile(rf"(?<![A-Za-z0-9_]){re.escape(symbol)}(?![A-Za-z0-9_])")


def find_missing_symbols(
    symbols: list[str],
    target_path: Path,
) -> list[str]:
    """Return symbols NOT mentioned in *target_path* (whole-word match)."""
    if not target_path.exists():
        return list(symbols)  # whole file missing → everything missing
    text = _read_text(target_path)
    missing: list[str] = []
    for sym in symbols:
        if not _symbol_pattern(sym).search(text):
            missing.append(sym)
    return missing


# ----------------------------------------------------------------------
# Main checks
# ----------------------------------------------------------------------

def run_checks(repo_root: Path) -> dict[str, Any]:
    """Run all helpfile-freshness checks; return a structured result."""
    agent_guide = repo_root / "AGENT_GUIDE.md"
    class_definitions = repo_root / "docs" / "ClassDefinitions.md"

    surface = collect_public_symbols()
    findings: dict[str, Any] = {
        "agent_guide_missing": {},
        "class_definitions_missing": {},
        "symbols_total": 0,
        "classes_total": 0,
    }

    for namespace, symbols in surface.items():
        findings["symbols_total"] += len(symbols)

        # AGENT_GUIDE.md should mention every public symbol (any prose context).
        missing_ag = find_missing_symbols(symbols, agent_guide)
        if missing_ag:
            findings["agent_guide_missing"][namespace] = missing_ag

        # ClassDefinitions.md should list every *class* (exclude functions / exceptions).
        classes = [s for s in symbols if symbol_is_class(namespace, s)]
        findings["classes_total"] += len(classes)
        missing_cd = find_missing_symbols(classes, class_definitions)
        if missing_cd:
            findings["class_definitions_missing"][namespace] = missing_cd

    return findings


# ----------------------------------------------------------------------
# Reporting
# ----------------------------------------------------------------------

def render_summary(findings: dict[str, Any], quiet: bool = False) -> str:
    n_missing_ag = sum(len(v) for v in findings["agent_guide_missing"].values())
    n_missing_cd = sum(len(v) for v in findings["class_definitions_missing"].values())
    total = n_missing_ag + n_missing_cd

    lines: list[str] = []
    if not quiet or total > 0:
        lines.append("Helpfile freshness check")
        lines.append(f"  total public symbols: {findings['symbols_total']}")
        lines.append(f"  total public classes: {findings['classes_total']}")
        lines.append(f"  AGENT_GUIDE.md missing:        {n_missing_ag}")
        lines.append(f"  docs/ClassDefinitions.md missing: {n_missing_cd}")

    if findings["agent_guide_missing"]:
        lines.append("")
        lines.append("MISSING FROM AGENT_GUIDE.md:")
        for namespace, names in findings["agent_guide_missing"].items():
            for name in names:
                lines.append(f"  - {namespace}.{name}")

    if findings["class_definitions_missing"]:
        lines.append("")
        lines.append("MISSING FROM docs/ClassDefinitions.md:")
        for namespace, names in findings["class_definitions_missing"].items():
            for name in names:
                lines.append(f"  - {namespace}.{name}")

    if total == 0 and not quiet:
        lines.append("")
        lines.append("Helpfile freshness OK.")

    return "\n".join(lines)


# ----------------------------------------------------------------------
# CLI
# ----------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=_REPO_ROOT_FOR_IMPORT,
        help="Path to the repository root (default: parent of tools/).",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Only print on failure (default: print summary always).",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit machine-readable JSON instead of human-readable text.",
    )
    args = parser.parse_args(argv)

    try:
        findings = run_checks(args.repo_root.resolve())
    except Exception as exc:
        print(f"error: helpfile check failed to run: {exc}", file=sys.stderr)
        return 2

    n_missing = sum(len(v) for v in findings["agent_guide_missing"].values()) + sum(
        len(v) for v in findings["class_definitions_missing"].values()
    )

    if args.json:
        print(json.dumps(findings, indent=2, default=str))
    else:
        out = render_summary(findings, quiet=args.quiet)
        if out:
            print(out)

    if n_missing > 0:
        print(
            f"\nHelpfile freshness FAILED ({n_missing} undocumented symbol(s)).",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
