#!/usr/bin/env python3
"""Compute side-by-side visual parity between MATLAB and Python figures.

Reads ``parity/visual_fidelity.yml`` and, for each entry, loads the
MATLAB helpfile PNG and its Python counterpart, normalises both to
800×600 grayscale, and computes the structural-similarity index (SSIM)
from :func:`skimage.metrics.structural_similarity`.

Outputs
-------
- ``parity/visual_fidelity_results.json`` — per-entry SSIM score,
  pass/fail flag, and metadata.
- ``docs/parity/visual_comparison.md`` — human-readable side-by-side
  index linking to GitHub-rendered PNGs.

Exit status
-----------
Returns nonzero when ``--fail-below-threshold`` is set and any non-skipped
entry falls below its per-entry threshold.  Use in CI to gate against
visual regression.

Notes
-----
SSIM is chosen over pHash (insensitive to scientifically-meaningful
axis-shift / axis-scale changes) and pixel-diff with tolerance (noise-
sensitive to font-rendering differences).  SSIM operates on luminance /
contrast / structure channels separately, robust to global brightness
shifts but sensitive to a curve moving across axes or a panel going
blank.  See the parity audit synthesis in PR #156 / #166.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import yaml
from PIL import Image
from skimage.metrics import structural_similarity as ssim


REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = REPO_ROOT / "parity" / "visual_fidelity.yml"
RESULTS_PATH = REPO_ROOT / "parity" / "visual_fidelity_results.json"
DOCS_PAGE = REPO_ROOT / "docs" / "parity" / "visual_comparison.md"
DEFAULT_MATLAB_ROOT = REPO_ROOT.parent / "nSTAT"

NORMALIZED_SIZE = (800, 600)


def _load_manifest() -> dict:
    return yaml.safe_load(MANIFEST_PATH.read_text(encoding="utf-8"))


def _resolve_matlab_path(rel: str, matlab_root: Path) -> Path:
    """Resolve a MATLAB PNG path relative to the MATLAB checkout."""
    return (matlab_root / rel).resolve()


def _resolve_python_path(rel: str) -> Path:
    """Resolve a Python PNG path relative to the Python repo root."""
    return (REPO_ROOT / rel).resolve()


def _load_grayscale(path: Path) -> np.ndarray | None:
    """Load an image, convert to grayscale 800×600 numpy array."""
    if not path.exists():
        return None
    img = Image.open(path).convert("L")
    img = img.resize(NORMALIZED_SIZE, Image.LANCZOS)
    return np.asarray(img, dtype=np.float64) / 255.0


def _compare_pair(matlab_path: Path, python_path: Path) -> tuple[float | None, str | None]:
    """Return ``(ssim_score, error_msg)``.  ``ssim_score`` is None on error."""
    m = _load_grayscale(matlab_path)
    if m is None:
        return None, f"MATLAB PNG missing at {matlab_path}"
    p = _load_grayscale(python_path)
    if p is None:
        return None, f"Python PNG missing at {python_path}"
    score = float(ssim(m, p, data_range=1.0))
    return score, None


def _write_results(results: list[dict]) -> None:
    RESULTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": 1,
        "metric": "ssim",
        "normalized_size": list(NORMALIZED_SIZE),
        "entries": results,
    }
    RESULTS_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def _write_docs_page(results: list[dict], matlab_root: Path) -> None:
    DOCS_PAGE.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Visual parity comparison",
        "",
        "Side-by-side MATLAB vs Python figure comparison, scored by",
        "structural-similarity index (SSIM).  This page is auto-generated by",
        "`tools/parity/build_visual_comparison.py` — do not hand-edit.",
        "",
        "SSIM ranges from `-1` (totally different) to `+1` (identical).  ",
        "Each entry has a per-figure threshold tuned to the figure's nature:",
        "deterministic plots aim for `≥ 0.70`; stochastic plots for `≥ 0.50`.",
        "",
        "MATLAB PNGs are sourced from the sibling `cajigaslab/nSTAT` "
        "checkout when running locally; the live docs site embeds the "
        "Python-side PNG only (since the MATLAB repo is not deployed).",
        "",
        "| Topic | Description | SSIM | Threshold | Pass | Notes |",
        "|---|---|---:|---:|:-:|---|",
    ]
    for r in results:
        if r.get("skipped"):
            marker = r.get("skip_reason", "skip")
            score_str = "—"
            pass_str = "↷"
        elif r.get("ssim") is None:
            marker = r.get("notes", "error")
            score_str = "—"
            pass_str = "?"
        else:
            score_str = f"{r['ssim']:.3f}"
            pass_str = "✓" if r["passed"] else "✗"
            marker = r.get("notes", "")
        # Collapse multi-line YAML notes onto one row (Markdown tables
        # can't span lines).  Empty strings get a dash to keep cells aligned.
        marker = " ".join(str(marker).split()) or "—"
        lines.append(
            f"| `{r['topic']}` | {r['figure_description']} | "
            f"{score_str} | {r['threshold']:.2f} | {pass_str} | {marker} |"
        )
    lines.append("")
    lines.append(
        "Regenerate with `make regen-visual-parity` "
        "(requires the sibling MATLAB checkout for full coverage)."
    )
    DOCS_PAGE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _summarize(results: list[dict]) -> tuple[int, int, int]:
    """Return ``(n_pass, n_fail, n_skip)``."""
    n_pass = sum(1 for r in results if r.get("ssim") is not None and r.get("passed"))
    n_fail = sum(
        1
        for r in results
        if not r.get("skipped")
        and r.get("ssim") is not None
        and not r.get("passed")
    )
    n_skip = sum(1 for r in results if r.get("skipped"))
    return n_pass, n_fail, n_skip


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--matlab-root",
        type=Path,
        default=DEFAULT_MATLAB_ROOT,
        help="MATLAB nSTAT checkout root (default: sibling ../nSTAT).",
    )
    parser.add_argument(
        "--fail-below-threshold",
        action="store_true",
        help="Exit nonzero if any non-skipped entry falls below its SSIM threshold.",
    )
    args = parser.parse_args(argv)

    if not MANIFEST_PATH.exists():
        print(f"ERROR: manifest not found at {MANIFEST_PATH}", file=sys.stderr)
        return 1

    payload = _load_manifest()
    entries = payload.get("entries", [])
    matlab_root = args.matlab_root.resolve()
    matlab_available = matlab_root.exists()

    results: list[dict] = []
    for entry in entries:
        topic = entry["topic"]
        threshold = float(entry.get("ssim_threshold", 0.70))
        result = {
            "topic": topic,
            "figure_description": entry.get("figure_description", ""),
            "matlab_png": entry["matlab_png"],
            "python_png": entry["python_png"],
            "threshold": threshold,
            "stochastic": bool(entry.get("stochastic", False)),
            "notes": entry.get("notes", ""),
        }
        if entry.get("skip_ci"):
            result["skipped"] = True
            result["skip_reason"] = entry.get("skip_reason", "marked skip_ci")
            results.append(result)
            continue
        if not matlab_available:
            result["ssim"] = None
            result["passed"] = False
            result["notes"] = (
                "matlab repo unavailable — local-only metric"
                if not result["notes"]
                else result["notes"]
            )
            results.append(result)
            continue
        m_path = _resolve_matlab_path(entry["matlab_png"], matlab_root)
        p_path = _resolve_python_path(entry["python_png"])
        score, err = _compare_pair(m_path, p_path)
        if score is None:
            result["ssim"] = None
            result["passed"] = False
            result["notes"] = err
        else:
            result["ssim"] = score
            result["passed"] = score >= threshold
        results.append(result)

    _write_results(results)
    _write_docs_page(results, matlab_root)

    n_pass, n_fail, n_skip = _summarize(results)
    total_scored = sum(1 for r in results if r.get("ssim") is not None)
    print(f"Visual parity: {n_pass}/{total_scored} pass, {n_fail} fail, {n_skip} skipped")
    for r in results:
        if r.get("ssim") is not None and not r.get("passed"):
            print(
                f"  FAIL [{r['topic']}] ssim={r['ssim']:.3f} "
                f"< threshold={r['threshold']:.2f}: {r['notes']}",
                file=sys.stderr,
            )

    if args.fail_below_threshold and n_fail > 0:
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
